image:
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - x86
  - x64

configuration:
  - Release

for:

-
  matrix:
    only:
      - platform: x86
        configuration: Release
  build_script:
    - .ci\build_windows_x86.bat

-
  matrix:
    only:
      - platform: x64
        configuration: Release
  build_script:
    - .ci\build_windows_x64.bat
