image:
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

for:

-
  matrix:
    only:
      - platform: x86
        configuration: Debug
  build_script:
    - scripts\build_debug_x86.bat

-
  matrix:
    only:
      - platform: x64
        configuration: Debug
  build_script:
    - scripts\build_debug_x64.bat

-
  matrix:
    only:
      - platform: x86
        configuration: Release
  build_script:
    - scripts\build_release_x86.bat

-
  matrix:
    only:
      - platform: x64
        configuration: Release
  build_script:
    - scripts\build_release_x64.bat
