version: "{build}"
shallow_clone: true
image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019 Preview
platform:
  - Win32
  - x64
build_script:
  - scripts\build_all.bat
test: off
