language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      addons: { apt: { sources: ubuntu-toolchain-r-test, packages: ["xorg-dev", "g++-6"] } }
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      dist: trusty
      addons: { apt: { sources: ubuntu-toolchain-r-test, packages: ["xorg-dev", "g++-7"] } }
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: trusty
      addons: { apt: { sources: ubuntu-toolchain-r-test, packages: ["xorg-dev", "g++-8"] } }
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      dist: trusty
      addons: { apt: { sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.8"], packages: ["xorg-dev", "clang-3.8", "g++-5"] } }
      env: MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
    - os: linux
      dist: trusty
      addons: { apt: { sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.9"], packages: ["xorg-dev", "clang-3.9", "g++-5"] } }
      env: MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - os: linux
      dist: trusty
      addons: { apt: { sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-4.0"], packages: ["xorg-dev", "clang-4.0", "g++-5"] } }
      env: MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - os: linux
      dist: trusty
      addons: { apt: { sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"], packages: ["xorg-dev", "clang-5.0", "g++-7"] } }
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: linux
      dist: trusty
      addons: { apt: { sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-6.0"], packages: ["xorg-dev", "clang-6.0", "g++-7"] } }
      env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - os: osx
      osx_image: xcode8.3
      compiler: clang
    - os: osx
      osx_image: xcode9
      compiler: clang
    - os: osx
      osx_image: xcode9.1
      compiler: clang
    - os: osx
      osx_image: xcode9.2
      compiler: clang
    - os: osx
      osx_image: xcode9.3
      compiler: clang
    - os: osx
      osx_image: xcode9.4
      compiler: clang
    - os: osx
      osx_image: xcode10
      compiler: clang
      addons: { homebrew: { packages: ["lcov"] } }
      after_success: ./scripts/upload_coverage.sh
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - ./scripts/build_all.sh
