git:
  depth: false
  quiet: true

language: cpp

jobs:
  include:

    #
    # linux (g++)
    #

    - os: linux
      dist: bionic
      stage: linux
      name: g++-7
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["g++-7"] } }
      env: CC=gcc-7 CXX=g++-7
      script: .ci/build_linux.sh

    - os: linux
      dist: bionic
      stage: linux
      name: g++-8
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["g++-8"] } }
      env: CC=gcc-8 CXX=g++-8
      script: .ci/build_linux.sh

    #
    # linux (clang++)
    #

    - os: linux
      dist: bionic
      stage: linux
      name: clang++-5.0
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["clang-5.0"] } }
      env: CC=clang-5.0 CXX=clang++-5.0
      script: .ci/build_linux.sh

    - os: linux
      dist: bionic
      stage: linux
      name: clang++-6.0
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["clang-6.0"] } }
      env: CC=clang-6.0 CXX=clang++-6.0
      script: .ci/build_linux.sh

    #
    # darwin
    #

    - os: osx
      osx_image: xcode10
      stage: darwin
      name: xcode10
      script: .ci/build_darwin.sh

    - os: osx
      osx_image: xcode11
      stage: darwin
      name: xcode11
      script: .ci/build_darwin.sh

    #
    # coverage
    #

    - os: osx
      osx_image: xcode10
      stage: coverage
      name: coverage
      addons: { homebrew: { packages: ["lcov"], update: true } }
      script: .ci/build_coverage.sh
