version: "{build}"
shallow_clone: true
image:
  - Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - Win32
  - x64
build_script:
  - mkdir build && cd build
  - cmake .. -A%PLATFORM%
  - cmake --build . --config %CONFIGURATION%
  - ..\build\%CONFIGURATION%\kari.exe
test: off
